name: Deploy Laravel App to cPanel

on:
  push:
    branches:
      - main # Change this to your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan cstarbd.com >> ~/.ssh/known_hosts

      - name: Deploy to cPanel
        run: |
          ssh speechth@cstarbd.com <<EOF
            cd cstarbd.com  # Change to your Laravel project directory
            git pull origin main   # Pull latest code
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            chmod -R 775 storage bootstrap/cache
            chown -R $USER:$USER storage bootstrap/cache
          EOF
