name: Deploy Laravel to cPanel via FTP

on:
  push:
    branches:
      - main # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftp
          port: ${{ secrets.PORT }}
          local-dir: ./
          server-dir: /public_html/ #
          timeout: 300000
          log-level: verbose
